"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Project = { id?: string; title: string; description: string; tags: string[]; repo_url: string; demo_url: string; markdown_content: string; is_visible: boolean };
const empty: Project = { title: "", description: "", tags: [], repo_url: "", demo_url: "", markdown_content: "", is_visible: true };

export default function Admin() {
  const router = useRouter(); const [projects, setProjects] = useState<Project[]>([]); const [form, setForm] = useState<Project>(empty); const [command, setCommand] = useState(""); const [message, setMessage] = useState("Loading project registry...");
  async function load() { const response = await fetch("/api/admin/projects", { cache: "no-store" }); if (response.status === 401) { router.replace("/"); return; } if (!response.ok) { setMessage((await response.json().catch(() => ({}))).error ?? "Unable to load projects."); return; } setProjects(await response.json()); setMessage(""); }
  useEffect(() => { void load(); }, []);
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.replace("/"); }
  async function runCommand(event: FormEvent) { event.preventDefault(); if (command.trim().toLowerCase() === "exit") await logout(); else setMessage(`Unknown command: ${command}`); setCommand(""); }
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/projects", { method: form.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) { setMessage("ERROR: " + ((await response.json().catch(() => ({}))).error ?? "save failed")); return; } setForm(empty); await load(); }
  async function remove(id: string) { await fetch("/api/admin/projects", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); await load(); }
  return <main className="cmd-window"><header className="cmd-titlebar"><span>▣ C:\\Windows\\System32\\cmd.exe - admin@yoonseo-portfolio</span><div><button onClick={logout}>[ Logout ]</button><button onClick={() => router.push("/")}>×</button></div></header><div className="cmd-body"><p>Microsoft Windows [Version 10.0.22631.3007]</p><p>(c) Yoonseo Corp. All rights reserved.</p><p className="cmd-green">ADMIN SESSION ACTIVE: Type commands or use the interactive manager below.</p><form className="cmd-command" onSubmit={runCommand}><label>C:\Admin\Projects&gt; <input autoFocus value={command} onChange={(event) => setCommand(event.target.value)} placeholder="type exit to logout" /></label></form>{message && <p className={message.startsWith("ERROR") ? "cmd-error" : "cmd-green"}>{message}</p>}<section className="cmd-panel"><div className="cmd-panel-title">[ PROJECT MANAGER ]</div><form className="cmd-form" onSubmit={save}><input placeholder="title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required /><input placeholder="description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><input placeholder="tags: react, nextjs" value={form.tags.join(", ")} onChange={(event) => setForm({ ...form, tags: event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean) })} /><input placeholder="repository url" value={form.repo_url} onChange={(event) => setForm({ ...form, repo_url: event.target.value })} /><input placeholder="demo url" value={form.demo_url} onChange={(event) => setForm({ ...form, demo_url: event.target.value })} /><textarea placeholder="markdown content" value={form.markdown_content} onChange={(event) => setForm({ ...form, markdown_content: event.target.value })} /><label><input type="checkbox" checked={form.is_visible} onChange={(event) => setForm({ ...form, is_visible: event.target.checked })} /> visible</label><button>{form.id ? "UPDATE PROJECT" : "ADD PROJECT"}</button></form></section><section className="cmd-panel"><div className="cmd-panel-title">[ PROJECTS.DAT ]</div>{projects.length === 0 ? <p>-- no projects found --</p> : <div className="cmd-project-list">{projects.map((project) => <div className="cmd-project" key={project.id}><span className="cmd-green">{project.is_visible ? "[ON]" : "[OFF]"}</span><strong>{project.title}</strong><span>{project.description}</span><button onClick={() => setForm(project)}>EDIT</button><button onClick={() => project.id && remove(project.id)}>DELETE</button></div>)}</div>}</section></div></main>;
}
