"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
type Project = { id?: string; title: string; description: string; tags: string[]; repo_url: string; demo_url: string; markdown_content: string; is_visible: boolean };
const empty: Project = { title: "", description: "", tags: [], repo_url: "", demo_url: "", markdown_content: "", is_visible: true };
export default function Admin() {
  const router = useRouter(); const [password, setPassword] = useState(""); const [authed, setAuthed] = useState(false); const [projects, setProjects] = useState<Project[]>([]); const [form, setForm] = useState<Project>(empty); const [message, setMessage] = useState("");
  async function load() { const r = await fetch("/api/admin/projects", { cache: "no-store" }); if (!r.ok) { setMessage((await r.json().catch(() => ({}))).error ?? "Unable to load projects."); return; } setAuthed(true); setProjects(await r.json()); setMessage(""); }
  useEffect(() => { void load(); }, []);
  async function login(e: FormEvent) { e.preventDefault(); setMessage("Authenticating..."); const r = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!r.ok) { setMessage("ACCESS DENIED: invalid password"); return; } setPassword(""); await load(); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.push("/"); }
  async function command(e: FormEvent) { e.preventDefault(); if (password.trim().toLowerCase() === "exit") await logout(); }
  async function save(e: FormEvent) { e.preventDefault(); const r = await fetch("/api/admin/projects", { method: form.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!r.ok) { setMessage("ERROR: " + ((await r.json().catch(() => ({}))).error ?? "save failed")); return; } setForm(empty); await load(); }
  async function remove(id: string) { await fetch("/api/admin/projects", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); await load(); }
  if (!authed) return <main className="cmd-window"><header className="cmd-titlebar"><span>▣ C:\\Windows\\System32\\cmd.exe - admin@yoonseo-portfolio</span><button onClick={() => router.push("/")}>×</button></header><section className="cmd-login"><p>Microsoft Windows [Version 10.0.22631.3007]</p><p>(c) Yoonseo Corp. All rights reserved.</p><p>ADMIN CONSOLE // AUTHENTICATION REQUIRED</p><form onSubmit={login}><label>C:\Users\Admin&gt; <input autoFocus type="password" placeholder="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button>ENTER</button></form>{message && <p className="cmd-error">{message}</p>}</section></main>;
  return <main className="cmd-window"><header className="cmd-titlebar"><span>▣ C:\\Windows\\System32\\cmd.exe - admin@yoonseo-portfolio</span><div><button onClick={logout}>[ Logout ]</button><button onClick={() => router.push("/")}>×</button></div></header><div className="cmd-body"><p>Microsoft Windows [Version 10.0.22631.3007]</p><p>(c) Yoonseo Corp. All rights reserved.</p><p className="cmd-green">ADMIN SESSION ACTIVE: Type commands or use the interactive manager below.</p><form className="cmd-command" onSubmit={command}><label>C:\Admin\Projects&gt; <input autoFocus value={password} onChange={(e) => setPassword(e.target.value)} placeholder="type exit to logout" /></label></form>{message && <p className="cmd-error">{message}</p>}<section className="cmd-panel"><div className="cmd-panel-title">[ PROJECT MANAGER ]</div><form className="cmd-form" onSubmit={save}><input placeholder="title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /><input placeholder="description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><input placeholder="tags: react, nextjs" value={form.tags.join(", ")} onChange={(e) => setForm({ ...form, tags: e.target.value.split(",").map((tag) => tag.trim()).filter(Boolean) })} /><input placeholder="repository url" value={form.repo_url} onChange={(e) => setForm({ ...form, repo_url: e.target.value })} /><input placeholder="demo url" value={form.demo_url} onChange={(e) => setForm({ ...form, demo_url: e.target.value })} /><textarea placeholder="markdown content" value={form.markdown_content} onChange={(e) => setForm({ ...form, markdown_content: e.target.value })} /><label><input type="checkbox" checked={form.is_visible} onChange={(e) => setForm({ ...form, is_visible: e.target.checked })} /> visible</label><button>{form.id ? "UPDATE PROJECT" : "ADD PROJECT"}</button></form></section><section className="cmd-panel"><div className="cmd-panel-title">[ PROJECTS.DAT ]</div>{projects.length === 0 ? <p>-- no projects found --</p> : <div className="cmd-project-list">{projects.map((project) => <div className="cmd-project" key={project.id}><span className="cmd-green">{project.is_visible ? "[ON]" : "[OFF]"}</span> <strong>{project.title}</strong><span>{project.description}</span><button onClick={() => setForm(project)}>EDIT</button><button onClick={() => project.id && remove(project.id)}>DELETE</button></div>)}</div>}</section></div></main>;
}
